---
# tasks file for dockerstart
    - name: Install Git
      package:
        name: git
        state: present
        update_cache: yes

    - name: Clone a github repository
      git:
        repo: git@github.com:EvgeniaKr/DockerImagePrivate.git
        dest: /home/debian/repos/DockerImages
        clone: yes
        update: yes
    
    - name: Create Docker bridge network
      community.docker.docker_network:
        name: my_bridge_network
        driver: bridge
        state: present

    - name: "Build Image Apache"
      docker_image:
        name: "apachename"        
        tag: latest
        build:
          path: /home/debian/repos/DockerImages/imageapache
          dockerfile: Dockerfile
        source: build
        state: present

    - name: "Build Image Nginx"
      docker_image:
        name: "nginxname"        
        tag: latest
        build:
          path: /home/debian/repos/DockerImages/imagenginx
        source: build
        state: present
        
    - name: Start container Apache
      community.docker.docker_container:
        image: apachename:latest
        name: apache-container
        state: started
        networks:
          - name: my_bridge_network
        ports:
          - "8081:8081"
          - "8084:8084"
          - "8085:8085"
        env:
          APACHE_RUN_USER: www-data
          APACHE_RUN_GROUP: www-data
        restart_policy: always
        state: started
        detach: true

    - name: Start container Nginx
      community.docker.docker_container:
        image: nginxname:latest
        name: nginx-container
        state: started
        networks:
          - name: my_bridge_network
        ports:
          - "80:80"
          - "443:443"
        restart_policy: always
        state: started
        detach: true
    

    