---
# tasks file for dockerstart
    - name: Install Git
      package:
        name: git
        state: present
        update_cache: yes

    - name: Clone a github private repository
      git:
        repo: "{{GIT_REPO}}"
        dest: "{{CLONE_DEST}}"
        accept_hostkey: yes
        key_file: "{{KEY_PATH}}"
        clone: yes
        update: yes
    
    - name: Create Docker bridge network
      community.docker.docker_network:
        name: "{{NAME_NETWORK}}"
        driver: bridge
        state: present

    - name: "Build Image Apache"
      docker_image:
        name: "{{NEME_APACHE_IMAGE}}"        
        tag: "{{TAG}}"
        build:
          path: "{{PATH_APACHE_IMAGE}}"
        source: build
        state: present

    - name: "Build Image Nginx"
      docker_image:
        name: "{{NAME_NGINX_IMAGE}}"        
        tag: "{{TAG}}"
        build:
          path: "{{PATH_NGINX_IMAGE}}"
        source: build
        state: present
        
    - name: Start container Apache
      community.docker.docker_container:
        image: "{{NEME_APACHE_IMAGE}}:{{TAG}}"
        name: "{{NAME_APACHE_CONTAINER}}"
        state: started
        networks:
          - name: "{{NAME_NETWORK}}"
        ports:
          - "8081:8081"
          - "8084:8084"
          - "8085:8085"
        env:
          APACHE_RUN_USER: www-data
          APACHE_RUN_GROUP: www-data
        restart_policy: always
        state: started
        detach: true

    - name: Start container Nginx
      community.docker.docker_container:
        image: "{{NAME_NGINX_IMAGE}}:{{TAG}}"
        name: "{{NAME_NGINX_CONTAINER}}"
        state: started
        networks:
          - name: "{{NAME_NETWORK}}"
        ports:
          - "80:80"
          - "443:443"
        restart_policy: always
        state: started
        detach: true
    

    