---
# tasks file for dockerinstall
- include_tasks: install_ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'

- include_tasks: install_amazon_linux.yml
  when: ansible_facts['os_family'] == 'RedHat'
