---
# tasks file for dockerinstall
- include_tasks: install_ubuntu.yml
  when: ansible_os_family == "Debian"

- include_tasks: install_amazon_linux.yml
  when: ansible_os_family == 'RedHat'
  
- name: Start Docker
  systemd:
    name: docker
    enabled: yes
    state: started