---
# tasks file for updateserver
- name: Update ubuntu
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Update linux
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'
